package mobit.eemr;

public interface IDef {

	int MBTPROBE_STANDART					=	0;
	int MBTPROBE_MOBITBLUETOOTH1			=	1;
	int MBTPROBE_MOBITBLUETOOTH2			=	2;
	int MBTPROBE_BLUSKYBLUETOOTH			=	3;

	int MBTMETERREADER_GENERICMETER			=	0;
	int MBTMETERREADER_OLDKOHLERMETER		=	1;
	int MBTMETERREADER_FEDERALFTS3DMETER	=	2;

	int MBTMETERREADER_READOUT				=	(1 << 0);
	int MBTMETERREADER_LONGREADOUT			=	(1 << 1);
	int MBTMETERREADER_PROGRAMMODE			=	(1 << 2);
	int MBTMETERREADER_PROFILEMODE			=	(1 << 3);
	int MBTMETERREADER_DLMS_COSEM			=	(1 << 4);

	int MBTMETERREADER_ENERGYPROFILE		=	(1 << 0);
	int MBTMETERREADER_CURRENTPROFILE		=	(1 << 1);
	int MBTMETERREADER_VOLTAGEPROFILE		=	(1 << 2);

	int MBTMETERREADER_FLAGLENGTH			=	 3;
	int MBTMETERREADER_MAXIDENTIFICATIONLENGTH	= 32;	// Elektromed "<1>EC25TP105BT0.77710839"
}
